# Videos Pipeline

In [1]:
# Import everything needed to edit/save/watch video clips
from moviepy.editor import VideoFileClip
from IPython.display import HTML

# load helper functions
%run -i "0. Functions_Clases Pipeline.py"
%run -i "Line.py"

# Load Camera calibration params
[ret, mtx, dist, rvecs, tvecs] = pickle.load(open( "pickle_data/camera_calibration_params.p", "rb" ) )


[NbConvertApp] Converting notebook 0. Functions_Clases Pipeline.ipynb to script
[NbConvertApp] Writing 19747 bytes to 0. Functions_Clases Pipeline.py


In [2]:
def process_frame(img):
    
    ###### Resize image
    img = resizeImage(img)

    ###### Undistort image
    undistorted = undistort_image(img, mtx, dist)
  
    ###### Color Enhancement

    imageCE = colorEnhancement(img)
   
    ###### GrayScale
    imageGray = grayscale(imageCE)


    ###### Gauss Smoothing
    imageGauss = gaussian_blur(imageGray,kernel_size=5) 
    
    #### Edge detection
    sbinary = sobel_thresh(imageGauss, sobel_kernel=5, x_thresh=[80,100], y_thresh=[40,100], mag_thresh=[50,255], dir_thresh=[100,200])

    #### ROI
    ysize =sbinary.shape[0]
    xsize =sbinary.shape[1]

    ROI_upperWidth = 350 #Width of the upper horizontal straight in px
    ROI_upperHeight = 300 #Height of the upper horizontal straight from the bottom of the image in px
    ROI_lowerWidth = 1000 #Width of the lower horizontal straight in px
    ROI_lowerHeight = 50  #Height of the lower horizontal straight  from the bottom of the image in px      

    limitLL = ((xsize/2)-(ROI_lowerWidth/2),ysize-ROI_lowerHeight);
    limitLR = (xsize - ((xsize/2)-(ROI_lowerWidth/2)),ysize-ROI_lowerHeight);
    limitUL = ((xsize/2)-(ROI_upperWidth/2), ysize-ROI_upperHeight);
    limitUR = ((xsize/2)+(ROI_upperWidth/2), ysize-ROI_upperHeight);
    vertices = np.array([[limitLL,limitUL,limitUR , limitLR]], dtype=np.int32)
    
    imageROI = region_of_interest(sbinary,vertices)

    
    #### Perspective transform
    warped_img,M, Minv = warp_image(imageROI, hwidth = 250 ,offset = 0, height = -600, overplotLines= False )
    
    #### Find lines
    
    # Find x line poitns based on histogram values
    leftx_base, rightx_base  = find_lane_x_points(warped_img)
    
    # Update x base points
    lineLeft.updateXbase(leftx_base)
    lineRight.updateXbase(rightx_base)
    
    
    #Speed up coef with area search
    #Left line
    if lineLeft.missdetections > 0 or np.any((lineLeft.recent_poly_fits == 0)):
        ## Find lane pixels
        leftx, lefty, rightx, righty, out_img = find_lane_pixels(warped_img, lineLeft.bestx, lineRight.bestx, showRectangles = False)
        
        ## Update lane pixels
        lineLeft.updatePixels(leftx, lefty)   

        # Search blindly image
        coeffs_fit_L, lineDetectedL, left_fitx, ploty, img_line  = fit_polynomial(out_img, lineLeft.allx, lineLeft.ally, drawPoly = False)
        
    else:
        # Search based on coefs
        leftx, lefty, coeffs_fit_L, lineDetectedL, left_fitx, out_img = search_around_poly(warped_img, lineLeft)
        lineLeft.updatePixels(leftx, lefty)  

    #Right line
    if lineRight.missdetections > 0 or np.any((lineRight.recent_poly_fits == 0)):
        ## Update lane pixels
        if not("rightx" in locals()) or not("righty" in locals()) :
            leftx, lefty, rightx, righty, out_img = find_lane_pixels(warped_img, lineLeft.bestx, lineRight.bestx, showRectangles = False)

        lineRight.updatePixels(rightx, righty)
        
        # Search blindly image
        coeffs_fit_R, lineDetectedR, right_fitx, ploty, img_line  = fit_polynomial(out_img, lineRight.allx, lineRight.ally, drawPoly = False)
    else:
        # Search based on coefs
        rightx, righty, coeffs_fit_R, lineDetectedR, right_fitx, out_img = search_around_poly(out_img, lineRight)   
        lineRight.updatePixels(rightx, righty)
        
           
    #Update line class instances
    lineLeft.updateCoeffsLine(lineDetectedL, coeffs_fit_L, left_fitx, lineLeft.poly_ploty,coefLimits=[0.01,1,100],movingAvg=5 )
    lineRight.updateCoeffsLine(lineDetectedR, coeffs_fit_R,right_fitx,lineRight.poly_ploty,coefLimits=[0.01,1,100],movingAvg=5 )
        

        
    #Sanity check line width
    if left_fitx.any and right_fitx.any:  # If vectors are empty do nothing
        # If separation ok, update stage vectors
        if rightSeparation(left_fitx, right_fitx, limitDist = 50):
            lineLeft.poly_plotx_staged = left_fitx 
            lineRight.poly_plotx_staged = right_fitx
        else: # If separation not ok, use stage vectors
            print("Wrong separation between lines")
            if len(lineLeft.poly_plotx_staged)>0 and len(lineRight.poly_plotx_staged)>0: 
                lineLeft.poly_plotx = lineLeft.poly_plotx_staged
                lineRight.poly_plotx = lineRight.poly_plotx_staged
                
            lineLeft.missdetections += 1
            lineRight.missdetections += 1
    
    ### Unwarp images
    
    #color_warp = np.zeros_like(out_img).astype(np.uint8)
    color_warp = out_img
    #color_warp = np.dstack((warp_zero, warp_zero, warp_zero))
    
    pts_left = np.array([np.transpose(np.vstack([lineLeft.poly_plotx, lineLeft.poly_ploty]))])
    pts_right = np.array([np.flipud(np.transpose(np.vstack([lineRight.poly_plotx, lineRight.poly_ploty])))])
    pts = np.hstack((pts_left, pts_right))
    
     
    #Draw the lane onto the warped blank image
    cv2.fillPoly(color_warp, np.int_([pts]), (0,255, 0))
    
    
    newwarp = cv2.warpPerspective(color_warp, M, (img.shape[1], img.shape[0])) 
    result = cv2.addWeighted(img, 1, newwarp, 0.8, 0)
    
    
    ### Anotate Radius of curvature
    diff, mean, text = checkRadius(lineLeft, lineRight )

    result_annotated = cv2.putText(result, text, org= (50, 50), fontFace=cv2.FONT_HERSHEY_SIMPLEX, 
                   fontScale=2, color= (255, 255, 255), thickness=2, lineType=cv2.LINE_AA)
    

    ### Anotate Vehicle position
    dev, text = calculateDeviation(result, lineLeft,lineRight,)

    result_annotated = cv2.putText(result, text, org= (50, 100), fontFace=cv2.FONT_HERSHEY_SIMPLEX, 
                       fontScale=2, color= (255, 255, 255), thickness=2, lineType=cv2.LINE_AA)
      
 
    #out = np.dstack((out_img*255, out_img*255, out_img*255))
    
    return result_annotated

In [ ]:
# Instanciate cLine classes
lineLeft = Line()
lineRight = Line()


white_output = 'output_videos/solidWhiteRight.mp4'
#clip1 = VideoFileClip("test_videos/project_video.mp4").subclip(0,10)
clip1 = VideoFileClip("test_videos/project_video.mp4")
white_clip = clip1.fl_image(process_frame) #NOTE: this function expects color images!!
%time white_clip.write_videofile(white_output, audio=False)

t:   0%|                                                            | 0/1260 [00:00<?, ?it/s, now=None]

21.949389422316813
Moviepy - Building video output_videos/solidWhiteRight.mp4.
Moviepy - Writing video output_videos/solidWhiteRight.mp4

36.03171154690267


t:   0%|                                                    | 3/1260 [00:00<05:23,  3.88it/s, now=None]

48.653856170090194


t:   0%|▏                                                   | 4/1260 [00:01<05:14,  3.99it/s, now=None]

47.076991795087224


t:   0%|▏                                                   | 5/1260 [00:01<05:05,  4.10it/s, now=None]

46.78718624371311


t:   0%|▏                                                   | 6/1260 [00:01<05:04,  4.12it/s, now=None]

40.824459001735875


t:   1%|▎                                                   | 7/1260 [00:01<05:01,  4.16it/s, now=None]

37.375828046504296


t:   1%|▎                                                   | 8/1260 [00:01<04:50,  4.32it/s, now=None]

34.01030880435155


t:   1%|▎                                                   | 9/1260 [00:02<04:54,  4.25it/s, now=None]

72.75598321902271
Wrong separation between lines


t:   1%|▍                                                  | 10/1260 [00:02<04:42,  4.43it/s, now=None]

37.24195371597875


t:   1%|▍                                                  | 11/1260 [00:02<04:47,  4.35it/s, now=None]

33.10690056060315


t:   1%|▍                                                  | 12/1260 [00:02<04:54,  4.24it/s, now=None]

33.63845128228229


t:   1%|▌                                                  | 13/1260 [00:03<04:45,  4.36it/s, now=None]

28.584310091316127


t:   1%|▌                                                  | 14/1260 [00:03<04:45,  4.36it/s, now=None]

33.338345976074095


t:   1%|▌                                                  | 15/1260 [00:03<04:50,  4.28it/s, now=None]

51.09025782434736
Wrong separation between lines


t:   1%|▋                                                  | 16/1260 [00:03<04:56,  4.19it/s, now=None]

26.68068746553803


t:   1%|▋                                                  | 17/1260 [00:04<04:55,  4.20it/s, now=None]

51.887659153322375
Wrong separation between lines


t:   1%|▋                                                  | 18/1260 [00:04<04:51,  4.26it/s, now=None]

32.39104080891741
42.09245179191629


t:   2%|▊                                                  | 20/1260 [00:04<04:45,  4.34it/s, now=None]

39.11809416257546


t:   2%|▊                                                  | 21/1260 [00:04<04:45,  4.34it/s, now=None]

31.888002808999545


t:   2%|▉                                                  | 22/1260 [00:05<04:54,  4.20it/s, now=None]

56.51709171295306
Wrong separation between lines


t:   2%|▉                                                  | 23/1260 [00:05<04:56,  4.17it/s, now=None]

21.480895794043818


t:   2%|▉                                                  | 24/1260 [00:05<05:14,  3.94it/s, now=None]

60.684235204140975
Wrong separation between lines


t:   2%|█                                                  | 25/1260 [00:05<05:08,  4.01it/s, now=None]

31.691651791642755


t:   2%|█                                                  | 26/1260 [00:06<05:03,  4.07it/s, now=None]

22.66405609219794


t:   2%|█                                                  | 27/1260 [00:06<04:56,  4.16it/s, now=None]

17.796384572661964


t:   2%|█▏                                                 | 28/1260 [00:06<04:56,  4.15it/s, now=None]

20.648122771597684


t:   2%|█▏                                                 | 29/1260 [00:06<04:57,  4.13it/s, now=None]

30.692374487134202


t:   2%|█▏                                                 | 30/1260 [00:07<04:53,  4.19it/s, now=None]

30.197152441270248


t:   2%|█▎                                                 | 31/1260 [00:07<04:50,  4.23it/s, now=None]

32.22391546834916


t:   3%|█▎                                                 | 32/1260 [00:07<04:48,  4.26it/s, now=None]

38.60085304445323


t:   3%|█▎                                                 | 33/1260 [00:07<04:51,  4.21it/s, now=None]

42.21694265368302
57.69902276171939


t:   3%|█▍                                                 | 34/1260 [00:08<04:43,  4.32it/s, now=None]

Wrong separation between lines


t:   3%|█▍                                                 | 35/1260 [00:08<04:37,  4.42it/s, now=None]

42.26082773066929


t:   3%|█▍                                                 | 36/1260 [00:08<04:46,  4.27it/s, now=None]

25.049825446864247


t:   3%|█▍                                                 | 37/1260 [00:08<04:45,  4.29it/s, now=None]

49.89206753679912


t:   3%|█▌                                                 | 38/1260 [00:09<04:49,  4.21it/s, now=None]

55.70342244837241
Wrong separation between lines


t:   3%|█▌                                                 | 39/1260 [00:09<04:52,  4.18it/s, now=None]

43.567794824546866


t:   3%|█▌                                                 | 40/1260 [00:09<04:49,  4.21it/s, now=None]

73.82874668524079
Wrong separation between lines
41.803752003486125


t:   3%|█▋                                                 | 41/1260 [00:09<04:40,  4.34it/s, now=None]

57.65877381560085
Wrong separation between lines


t:   3%|█▋                                                 | 42/1260 [00:09<04:29,  4.52it/s, now=None]

In [ ]:
HTML("""
<video width="960" height="540" controls>
  <source src="{0}">
</video>
""".format(white_output))

In [ ]:
# Instanciate cLine classes
lineLeft = Line()
lineRight = Line()


challenge_output = 'output_videos/challenge_video.mp4'
clip2 = VideoFileClip("test_videos/challenge_video.mp4")

challenge_clip = clip2.fl_image(process_frame) #NOTE: this function expects color images!!
%time challenge_clip.write_videofile(challenge_output, audio=False)

t:   0%|                                                             | 0/485 [00:00<?, ?it/s, now=None]

Wrong separation between lines
Moviepy - Building video output_videos/challenge_video.mp4.
Moviepy - Writing video output_videos/challenge_video.mp4

Wrong separation between lines


t:   1%|▎                                                    | 3/485 [00:00<01:49,  4.39it/s, now=None]

Wrong separation between lines


t:   1%|▍                                                    | 4/485 [00:00<01:46,  4.51it/s, now=None]

Wrong separation between lines


t:   1%|▌                                                    | 5/485 [00:01<01:46,  4.49it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   1%|▊                                                    | 7/485 [00:01<01:38,  4.83it/s, now=None]

Wrong separation between lines


t:   2%|▊                                                    | 8/485 [00:01<01:40,  4.76it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   2%|█                                                   | 10/485 [00:02<01:40,  4.72it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   3%|█▍                                                  | 13/485 [00:02<01:34,  5.00it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   3%|█▌                                                  | 14/485 [00:02<01:33,  5.01it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   3%|█▋                                                  | 16/485 [00:03<01:36,  4.87it/s, now=None]

Wrong separation between lines


t:   4%|█▊                                                  | 17/485 [00:03<01:38,  4.76it/s, now=None]

Wrong separation between lines


t:   4%|█▉                                                  | 18/485 [00:03<01:38,  4.75it/s, now=None]

Wrong separation between lines
missdetection
[ 3.88121917e-04 -4.51133390e-01  1.26769939e+02]


t:   4%|██▏                                                 | 20/485 [00:04<01:39,  4.67it/s, now=None]

Wrong separation between lines


t:   4%|██▎                                                 | 21/485 [00:04<01:40,  4.61it/s, now=None]

missdetection
[ 3.23327570e-04 -3.92034767e-01  1.18247394e+02]


t:   5%|██▎                                                 | 22/485 [00:04<01:43,  4.47it/s, now=None]

Wrong separation between lines


t:   5%|██▍                                                 | 23/485 [00:04<01:44,  4.42it/s, now=None]

Wrong separation between lines


t:   5%|██▌                                                 | 24/485 [00:05<01:39,  4.61it/s, now=None]

missdetection
[-3.91187656e-04  6.66311776e-01 -2.72039283e+02]
Wrong separation between lines
missdetection
[-3.04217208e-04  5.95086355e-01 -2.64485956e+02]
Wrong separation between lines


t:   5%|██▊                                                 | 26/485 [00:05<01:34,  4.87it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   6%|███                                                 | 28/485 [00:05<01:34,  4.84it/s, now=None]

Wrong separation between lines


t:   6%|███                                                 | 29/485 [00:06<01:36,  4.74it/s, now=None]

Wrong separation between lines


t:   6%|███▏                                                | 30/485 [00:06<01:36,  4.70it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   7%|███▌                                                | 33/485 [00:06<01:27,  5.14it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   7%|███▋                                                | 34/485 [00:07<01:28,  5.09it/s, now=None]

Wrong separation between lines


t:   7%|███▊                                                | 35/485 [00:07<01:31,  4.91it/s, now=None]

Wrong separation between lines
missdetection
[ 5.88283123e-04 -5.55563861e-01  1.08435647e+02]
Wrong separation between lines

t:   7%|███▊                                                | 36/485 [00:07<01:31,  4.91it/s, now=None]

t:   8%|███▉                                                | 37/485 [00:07<01:32,  4.86it/s, now=None]

missdetection
[ 4.89661634e-04 -4.79132519e-01  1.03889224e+02]
Wrong separation between lines


t:   8%|████                                                | 38/485 [00:07<01:33,  4.79it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:   8%|████▎                                               | 40/485 [00:08<01:29,  4.96it/s, now=None]

missdetection
[ 5.55666006e-04 -6.70179015e-01  2.03040151e+02]
Wrong separation between lines


t:   8%|████▍                                               | 41/485 [00:08<01:31,  4.86it/s, now=None]

missdetection
[ 5.12295642e-04 -6.26626738e-01  1.94158000e+02]
Wrong separation between lines
missdetection
[-2.60848507e-04  4.56208916e-01 -1.85649081e+02]
Wrong separation between lines


t:   9%|████▌                                               | 43/485 [00:08<01:26,  5.11it/s, now=None]

missdetection
[ 1.68381823e-04 -3.15612796e-01  1.44716637e+02]
Wrong separation between lines


t:   9%|████▋                                               | 44/485 [00:09<01:33,  4.73it/s, now=None]

missdetection
[ 4.55663179e-04 -6.84008682e-01  2.59490225e+02]
Wrong separation between lines


t:   9%|████▉                                               | 46/485 [00:09<01:29,  4.89it/s, now=None]

missdetection
[ 5.56803165e-04 -8.00952393e-01  2.92653903e+02]
Wrong separation between lines
missdetection
[ 6.17040691e-04 -9.20770856e-01  3.47723771e+02]
Wrong separation between lines


t:  10%|█████                                               | 47/485 [00:09<01:29,  4.87it/s, now=None]

missdetection
[ 9.31840978e-04 -1.28891973e+00  4.51951664e+02]
Wrong separation between lines


t:  10%|█████▏                                              | 48/485 [00:10<01:32,  4.75it/s, now=None]

missdetection
[ 7.21058446e-04 -1.01689692e+00  3.68010814e+02]
Wrong separation between lines


t:  10%|█████▎                                              | 49/485 [00:10<01:30,  4.81it/s, now=None]

missdetection
[ 1.30344763e-04  9.35661144e-02 -1.18941561e+02]
Wrong separation between lines


t:  10%|█████▎                                              | 50/485 [00:10<01:30,  4.79it/s, now=None]

Wrong separation between lines


t:  11%|█████▍                                              | 51/485 [00:10<01:31,  4.73it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  11%|█████▋                                              | 53/485 [00:11<01:31,  4.73it/s, now=None]

Wrong separation between lines


t:  11%|█████▊                                              | 54/485 [00:11<01:32,  4.67it/s, now=None]

Wrong separation between lines


t:  11%|█████▉                                              | 55/485 [00:11<01:34,  4.55it/s, now=None]

Wrong separation between lines


t:  12%|██████                                              | 56/485 [00:11<01:35,  4.51it/s, now=None]

Wrong separation between lines


t:  12%|██████                                              | 57/485 [00:12<01:36,  4.44it/s, now=None]

Wrong separation between lines


t:  12%|██████▏                                             | 58/485 [00:12<01:34,  4.52it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  12%|██████▍                                             | 60/485 [00:12<01:30,  4.69it/s, now=None]

Wrong separation between lines


t:  13%|██████▌                                             | 61/485 [00:12<01:31,  4.63it/s, now=None]

Wrong separation between lines


t:  13%|██████▋                                             | 62/485 [00:13<01:32,  4.59it/s, now=None]

missdetection
[-5.25618968e-04  5.65611218e-01 -1.34015346e+02]
Wrong separation between lines


t:  13%|██████▊                                             | 63/485 [00:13<01:30,  4.64it/s, now=None]

missdetection
[-4.51237557e-04  5.14351817e-01 -1.34365121e+02]
Wrong separation between lines
missdetection


t:  13%|██████▊                                             | 64/485 [00:13<01:28,  4.73it/s, now=None]

[-3.07499877e-04  3.82734871e-01 -1.15212352e+02]
Wrong separation between lines


t:  13%|██████▉                                             | 65/485 [00:13<01:30,  4.64it/s, now=None]

Wrong separation between lines


t:  14%|███████                                             | 66/485 [00:13<01:31,  4.56it/s, now=None]

missdetection
[-6.52264019e-04  6.74765879e-01 -1.48429167e+02]
Wrong separation between lines


t:  14%|███████▏                                            | 67/485 [00:14<01:29,  4.65it/s, now=None]

missdetection
[-6.92417570e-04  7.18929302e-01 -1.58833922e+02]
Wrong separation between lines


t:  14%|███████▎                                            | 68/485 [00:14<01:29,  4.67it/s, now=None]

Wrong separation between lines


t:  14%|███████▍                                            | 69/485 [00:14<01:31,  4.55it/s, now=None]

Wrong separation between lines
missdetection
[-6.75243699e-04  6.77358480e-01 -1.38499697e+02]
Wrong separation between lines


t:  15%|███████▌                                            | 71/485 [00:14<01:23,  4.94it/s, now=None]

missdetection
[-5.70921443e-04  5.68502650e-01 -1.12195758e+02]
Wrong separation between lines


t:  15%|███████▋                                            | 72/485 [00:15<01:25,  4.84it/s, now=None]

missdetection
[-6.68143416e-04  6.85764342e-01 -1.46038360e+02]
Wrong separation between lines


t:  15%|███████▊                                            | 73/485 [00:15<01:26,  4.75it/s, now=None]

Wrong separation between lines
missdetection
[ 1.43637142e-03 -2.06009778e+00  7.46814392e+02]
Wrong separation between lines


t:  15%|████████                                            | 75/485 [00:15<01:24,  4.85it/s, now=None]

missdetection
[ 1.31549431e-03 -1.85523371e+00  6.64127100e+02]
Wrong separation between lines
missdetection
[ 1.62133012e-03 -2.28832589e+00  8.17447674e+02]
Wrong separation between lines


t:  16%|████████▎                                           | 77/485 [00:16<01:23,  4.90it/s, now=None]

missdetection
[ 1.67212500e-03 -2.30376675e+00  8.04294726e+02]
Wrong separation between lines


t:  16%|████████▎                                           | 78/485 [00:16<01:26,  4.68it/s, now=None]

missdetection
[ 1.17992656e-03 -1.44211543e+00  4.41980415e+02]
Wrong separation between lines


t:  16%|████████▍                                           | 79/485 [00:16<01:26,  4.69it/s, now=None]

missdetection
[ 9.02718718e-04 -1.06589185e+00  3.14482300e+02]
Wrong separation between lines


t:  16%|████████▌                                           | 80/485 [00:16<01:27,  4.60it/s, now=None]

Wrong separation between lines


t:  17%|████████▋                                           | 81/485 [00:17<01:28,  4.54it/s, now=None]

Wrong separation between lines


t:  17%|████████▊                                           | 82/485 [00:17<01:28,  4.53it/s, now=None]

Wrong separation between lines


t:  17%|████████▉                                           | 83/485 [00:17<01:28,  4.54it/s, now=None]

Wrong separation between lines


t:  17%|█████████                                           | 84/485 [00:17<01:28,  4.53it/s, now=None]

Wrong separation between lines


t:  18%|█████████                                           | 85/485 [00:18<01:28,  4.51it/s, now=None]

missdetection
[ 8.36575190e-04 -1.07581614e+00  3.50257941e+02]
Wrong separation between lines
Wrong separation between lines


t:  18%|█████████▎                                          | 87/485 [00:18<01:25,  4.64it/s, now=None]

Wrong separation between lines


t:  18%|█████████▍                                          | 88/485 [00:18<01:26,  4.58it/s, now=None]

Wrong separation between lines


t:  18%|█████████▌                                          | 89/485 [00:18<01:27,  4.54it/s, now=None]

missdetection
[-4.08875794e-04  4.97363480e-01 -1.40708707e+02]
Wrong separation between lines


t:  19%|█████████▋                                          | 90/485 [00:19<01:25,  4.65it/s, now=None]

Wrong separation between lines


t:  19%|█████████▊                                          | 91/485 [00:19<01:25,  4.63it/s, now=None]

missdetection
[-4.90121421e-04  6.10877249e-01 -1.83440009e+02]


t:  19%|█████████▊                                          | 92/485 [00:19<01:28,  4.45it/s, now=None]

Wrong separation between lines


t:  19%|█████████▉                                          | 93/485 [00:19<01:28,  4.42it/s, now=None]

Wrong separation between lines


t:  19%|██████████                                          | 94/485 [00:19<01:28,  4.43it/s, now=None]

Wrong separation between lines


t:  20%|██████████▏                                         | 95/485 [00:20<01:27,  4.44it/s, now=None]

Wrong separation between lines


t:  20%|██████████▎                                         | 96/485 [00:20<01:26,  4.51it/s, now=None]

Wrong separation between lines


t:  20%|██████████▍                                         | 97/485 [00:20<01:27,  4.45it/s, now=None]

missdetection
[ 5.16125895e-04 -6.43590599e-01  2.02897197e+02]
Wrong separation between lines


t:  20%|██████████▌                                         | 98/485 [00:20<01:26,  4.47it/s, now=None]

missdetection
[-4.71180762e-04  5.17050843e-01 -1.28649811e+02]
Wrong separation between lines


t:  20%|██████████▌                                         | 99/485 [00:21<01:25,  4.53it/s, now=None]

missdetection
[-4.70587370e-04  5.07874605e-01 -1.21248910e+02]
Wrong separation between lines
missdetection
[-6.10294751e-04  6.54759224e-01 -1.55475861e+02]


t:  21%|██████████▌                                        | 100/485 [00:21<01:23,  4.62it/s, now=None]

Wrong separation between lines
missdetection
[-6.05596457e-04  6.39573487e-01 -1.46842222e+02]
Wrong separation between lines


t:  21%|██████████▋                                        | 102/485 [00:21<01:20,  4.77it/s, now=None]

missdetection
[-4.59125249e-04  5.44542389e-01 -1.50048755e+02]
Wrong separation between lines


t:  21%|██████████▊                                        | 103/485 [00:21<01:21,  4.70it/s, now=None]

missdetection
[-3.77183047e-04  4.82581777e-01 -1.46297633e+02]
Wrong separation between lines


t:  21%|██████████▉                                        | 104/485 [00:22<01:22,  4.60it/s, now=None]

missdetection
[-3.86020719e-04  4.82680807e-01 -1.41924603e+02]
Wrong separation between lines
missdetection


t:  22%|███████████                                        | 105/485 [00:22<01:20,  4.71it/s, now=None]

[-4.58568037e-04  5.39784732e-01 -1.48764152e+02]
Wrong separation between lines


t:  22%|███████████▏                                       | 106/485 [00:22<01:19,  4.75it/s, now=None]

missdetection
[ 6.22643427e-04 -7.81682428e-01  2.48097788e+02]
Wrong separation between lines


t:  22%|███████████▎                                       | 107/485 [00:22<01:20,  4.71it/s, now=None]

missdetection
[ 1.09105986e-03 -1.41135303e+00  4.63537105e+02]
Wrong separation between lines


t:  22%|███████████▎                                       | 108/485 [00:23<01:22,  4.56it/s, now=None]

missdetection
[ 7.13689814e-04 -8.82270729e-01  2.74527191e+02]
Wrong separation between lines


t:  22%|███████████▍                                       | 109/485 [00:23<01:21,  4.62it/s, now=None]

missdetection
[ 2.47616603e-04 -3.37207948e-01  1.21010776e+02]
Wrong separation between lines
missdetection
[ 1.03660447e-03 -1.33801854e+00  4.35941514e+02]
Wrong separation between lines


t:  23%|███████████▋                                       | 111/485 [00:23<01:19,  4.68it/s, now=None]

missdetection
[ 1.03505816e-03 -1.28188695e+00  3.98336307e+02]
Wrong separation between lines


t:  23%|███████████▊                                       | 112/485 [00:23<01:21,  4.55it/s, now=None]

missdetection
[-3.94421392e-04  4.59898401e-01 -1.23366248e+02]
Wrong separation between lines
missdetection
[-5.08797208e-04  5.73216748e-01 -1.46928235e+02]
Wrong separation between lines


t:  24%|███████████▉                                       | 114/485 [00:24<01:20,  4.62it/s, now=None]

missdetection
[-5.06309196e-04  5.33300430e-01 -1.19991551e+02]
Wrong separation between lines


t:  24%|████████████                                       | 115/485 [00:24<01:21,  4.54it/s, now=None]

missdetection
[-6.43821922e-04  7.04969599e-01 -1.73238415e+02]
Wrong separation between lines


t:  24%|████████████▏                                      | 116/485 [00:24<01:20,  4.58it/s, now=None]

missdetection
[-8.65521200e-04  9.11517378e-01 -2.10561467e+02]
Wrong separation between lines


t:  24%|████████████▎                                      | 117/485 [00:24<01:20,  4.55it/s, now=None]

missdetection
[-2.82430681e-04  3.76424874e-01 -1.18356104e+02]
Wrong separation between lines


t:  24%|████████████▍                                      | 118/485 [00:25<01:19,  4.62it/s, now=None]

Wrong separation between lines


t:  25%|████████████▌                                      | 119/485 [00:25<01:19,  4.63it/s, now=None]

Wrong separation between lines


t:  25%|████████████▌                                      | 120/485 [00:25<01:18,  4.65it/s, now=None]

Wrong separation between lines


t:  25%|████████████▋                                      | 121/485 [00:25<01:20,  4.53it/s, now=None]

Wrong separation between lines


t:  25%|████████████▊                                      | 122/485 [00:26<01:22,  4.40it/s, now=None]

missdetection
[ 2.58717037e-04 -3.32312033e-01  1.10475260e+02]
Wrong separation between lines


t:  25%|████████████▉                                      | 123/485 [00:26<01:21,  4.43it/s, now=None]

missdetection
[ 2.63072627e-04 -3.27857483e-01  1.05511092e+02]
Wrong separation between lines


t:  26%|█████████████                                      | 124/485 [00:26<01:20,  4.49it/s, now=None]

missdetection
[ 3.02640561e-04 -4.02506853e-01  1.32311568e+02]
missdetection
[ 5.19313171e-04 -6.52714784e-01  2.08139180e+02]
Wrong separation between lines


t:  26%|█████████████▏                                     | 125/485 [00:26<01:20,  4.47it/s, now=None]

missdetection
[ 6.22540268e-04 -8.18752694e-01  2.68514860e+02]
missdetection
[ 7.82900802e-04 -9.67952403e-01  3.00109086e+02]
Wrong separation between lines


t:  26%|█████████████▏                                     | 126/485 [00:26<01:19,  4.51it/s, now=None]

missdetection
[ 7.76551491e-04 -1.05775520e+00  3.58710757e+02]
missdetection
[ 1.01114211e-03 -1.31181020e+00  4.28309807e+02]
Wrong separation between lines


t:  26%|█████████████▎                                     | 127/485 [00:27<01:19,  4.49it/s, now=None]

missdetection
[ 8.67127367e-04 -1.17447713e+00  3.97735784e+02]
missdetection
[ 1.19543365e-03 -1.55027723e+00  5.05181542e+02]
Wrong separation between lines


t:  26%|█████████████▍                                     | 128/485 [00:27<01:18,  4.54it/s, now=None]

missdetection
[ 1.09356858e-03 -1.48831578e+00  5.05864762e+02]
missdetection
[ 1.32795239e-03 -1.75370828e+00  5.82297818e+02]
Wrong separation between lines


t:  27%|█████████████▌                                     | 129/485 [00:27<01:19,  4.45it/s, now=None]

missdetection
[ 1.19723399e-03 -1.67078149e+00  5.81977410e+02]
missdetection
[ 1.42787502e-03 -1.92356769e+00  6.51769261e+02]
Wrong separation between lines


t:  27%|█████████████▋                                     | 130/485 [00:27<01:19,  4.49it/s, now=None]

missdetection
[ 1.25546646e-03 -1.73695307e+00  6.00814931e+02]
missdetection
[ 1.53022199e-03 -2.10141993e+00  7.25582512e+02]
Wrong separation between lines
missdetection
[ 1.34814637e-03 -1.85684313e+00  6.39694117e+02]
missdetection
[ 1.55210322e-03 -2.17180659e+00  7.63480097e+02]
Wrong separation between lines


t:  27%|█████████████▉                                     | 132/485 [00:28<01:14,  4.72it/s, now=None]

missdetection
[ 1.35653531e-03 -1.87812386e+00  6.50711455e+02]
missdetection
[ 1.54029324e-03 -2.17601831e+00  7.71989761e+02]
Wrong separation between lines


t:  27%|█████████████▉                                     | 133/485 [00:28<01:14,  4.73it/s, now=None]

missdetection
[ 1.35794186e-03 -1.85881298e+00  6.36605292e+02]
missdetection
[ 1.55630658e-03 -2.18657925e+00  7.71480094e+02]
Wrong separation between lines


t:  28%|██████████████                                     | 134/485 [00:28<01:14,  4.70it/s, now=None]

missdetection
[ 1.37216797e-03 -1.86003832e+00  6.32979495e+02]
missdetection
[ 1.55782687e-03 -2.18816581e+00  7.71880493e+02]
Wrong separation between lines
missdetection
[ 1.38436442e-03 -1.87587347e+00  6.34792783e+02]
missdetection
[-3.47864184e-04  4.13883371e-01 -1.15516070e+02]


t:  28%|██████████████▏                                    | 135/485 [00:28<01:13,  4.78it/s, now=None]

Wrong separation between lines


t:  28%|██████████████▎                                    | 136/485 [00:29<01:14,  4.65it/s, now=None]

missdetection
[ 1.38434312e-03 -1.87584434e+00  6.34792832e+02]
missdetection
[-4.54176829e-04  5.25824355e-01 -1.42269891e+02]
Wrong separation between lines


t:  28%|██████████████▍                                    | 137/485 [00:29<01:15,  4.62it/s, now=None]

missdetection
[ 1.38406616e-03 -1.87546560e+00  6.34793470e+02]
Wrong separation between lines


t:  28%|██████████████▌                                    | 138/485 [00:29<01:17,  4.50it/s, now=None]

missdetection
[ 1.38372529e-03 -1.87499946e+00  6.34794254e+02]
Wrong separation between lines


t:  29%|██████████████▌                                    | 139/485 [00:29<01:15,  4.57it/s, now=None]

missdetection
[ 7.71069098e-04 -1.01989839e+00  3.36998378e+02]
Wrong separation between lines


t:  29%|██████████████▋                                    | 140/485 [00:29<01:14,  4.65it/s, now=None]

Wrong separation between lines


t:  29%|██████████████▊                                    | 141/485 [00:30<01:16,  4.52it/s, now=None]

Wrong separation between lines
missdetection
[ 1.35466146e-03 -1.83550490e+00  6.21554157e+02]


t:  29%|██████████████▉                                    | 142/485 [00:30<01:14,  4.62it/s, now=None]

Wrong separation between lines


t:  29%|███████████████                                    | 143/485 [00:30<01:14,  4.59it/s, now=None]

missdetection
[ 1.35470407e-03 -1.83556317e+00  6.21554059e+02]
Wrong separation between lines


t:  30%|███████████████▏                                   | 144/485 [00:30<01:15,  4.49it/s, now=None]

Wrong separation between lines


t:  30%|███████████████▏                                   | 145/485 [00:31<01:15,  4.51it/s, now=None]

Wrong separation between lines


t:  30%|███████████████▎                                   | 146/485 [00:31<01:14,  4.53it/s, now=None]

Wrong separation between lines


t:  30%|███████████████▍                                   | 147/485 [00:31<01:13,  4.58it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  31%|███████████████▋                                   | 149/485 [00:31<01:11,  4.72it/s, now=None]

Wrong separation between lines


t:  31%|███████████████▊                                   | 150/485 [00:32<01:12,  4.61it/s, now=None]

Wrong separation between lines


t:  31%|███████████████▉                                   | 151/485 [00:32<01:12,  4.60it/s, now=None]

Wrong separation between lines


t:  31%|███████████████▉                                   | 152/485 [00:32<01:12,  4.61it/s, now=None]

Wrong separation between lines


t:  32%|████████████████                                   | 153/485 [00:32<01:13,  4.54it/s, now=None]

Wrong separation between lines


t:  32%|████████████████▏                                  | 154/485 [00:33<01:14,  4.45it/s, now=None]

Wrong separation between lines


t:  32%|████████████████▎                                  | 155/485 [00:33<01:13,  4.51it/s, now=None]

Wrong separation between lines


t:  32%|████████████████▍                                  | 156/485 [00:33<01:13,  4.47it/s, now=None]

Wrong separation between lines


t:  32%|████████████████▌                                  | 157/485 [00:33<01:13,  4.43it/s, now=None]

Wrong separation between lines


t:  33%|████████████████▌                                  | 158/485 [00:33<01:14,  4.38it/s, now=None]

Wrong separation between lines


t:  33%|████████████████▋                                  | 159/485 [00:34<01:15,  4.34it/s, now=None]

Wrong separation between lines


t:  33%|████████████████▊                                  | 160/485 [00:34<01:13,  4.43it/s, now=None]

Wrong separation between lines


t:  33%|████████████████▉                                  | 161/485 [00:34<01:12,  4.44it/s, now=None]

Wrong separation between lines


t:  34%|█████████████████▏                                 | 163/485 [00:35<01:10,  4.55it/s, now=None]

Wrong separation between lines


t:  34%|█████████████████▏                                 | 164/485 [00:35<01:09,  4.62it/s, now=None]

Wrong separation between lines


t:  34%|█████████████████▎                                 | 165/485 [00:35<01:09,  4.61it/s, now=None]

Wrong separation between lines


t:  34%|█████████████████▍                                 | 166/485 [00:35<01:09,  4.56it/s, now=None]

Wrong separation between lines


t:  34%|█████████████████▌                                 | 167/485 [00:35<01:10,  4.53it/s, now=None]

Wrong separation between lines


t:  35%|█████████████████▋                                 | 168/485 [00:36<01:09,  4.54it/s, now=None]

Wrong separation between lines


t:  35%|█████████████████▊                                 | 169/485 [00:36<01:10,  4.49it/s, now=None]

Wrong separation between lines


t:  35%|█████████████████▉                                 | 170/485 [00:36<01:09,  4.53it/s, now=None]

Wrong separation between lines


t:  35%|█████████████████▉                                 | 171/485 [00:36<01:09,  4.49it/s, now=None]

Wrong separation between lines


t:  35%|██████████████████                                 | 172/485 [00:37<01:09,  4.51it/s, now=None]

Wrong separation between lines


t:  36%|██████████████████▏                                | 173/485 [00:37<01:10,  4.44it/s, now=None]

Wrong separation between lines


t:  36%|██████████████████▎                                | 174/485 [00:37<01:10,  4.44it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  36%|██████████████████▌                                | 176/485 [00:37<01:07,  4.58it/s, now=None]

Wrong separation between lines


t:  36%|██████████████████▌                                | 177/485 [00:38<01:06,  4.67it/s, now=None]

Wrong separation between lines


t:  37%|██████████████████▋                                | 178/485 [00:38<01:07,  4.56it/s, now=None]

Wrong separation between lines


t:  37%|██████████████████▊                                | 179/485 [00:38<01:06,  4.62it/s, now=None]

Wrong separation between lines


t:  37%|███████████████████                                | 181/485 [00:39<01:07,  4.48it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  38%|███████████████████▏                               | 183/485 [00:39<01:03,  4.79it/s, now=None]

Wrong separation between lines


t:  38%|███████████████████▎                               | 184/485 [00:39<01:05,  4.59it/s, now=None]

Wrong separation between lines


t:  38%|███████████████████▍                               | 185/485 [00:39<01:05,  4.60it/s, now=None]

Wrong separation between lines


t:  38%|███████████████████▌                               | 186/485 [00:40<01:03,  4.70it/s, now=None]

Wrong separation between lines


t:  39%|███████████████████▋                               | 187/485 [00:40<01:04,  4.59it/s, now=None]

Wrong separation between lines


t:  39%|███████████████████▊                               | 188/485 [00:40<01:05,  4.54it/s, now=None]

Wrong separation between lines


t:  39%|███████████████████▊                               | 189/485 [00:40<01:06,  4.43it/s, now=None]

Wrong separation between lines


t:  39%|███████████████████▉                               | 190/485 [00:41<01:05,  4.49it/s, now=None]

Wrong separation between lines


t:  39%|████████████████████                               | 191/485 [00:41<01:05,  4.52it/s, now=None]

Wrong separation between lines


t:  40%|████████████████████▏                              | 192/485 [00:41<01:05,  4.49it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  40%|████████████████████▍                              | 194/485 [00:41<01:02,  4.66it/s, now=None]

Wrong separation between lines


t:  40%|████████████████████▌                              | 195/485 [00:42<01:02,  4.63it/s, now=None]

Wrong separation between lines


t:  40%|████████████████████▌                              | 196/485 [00:42<01:04,  4.50it/s, now=None]

Wrong separation between lines


t:  41%|████████████████████▋                              | 197/485 [00:42<01:02,  4.58it/s, now=None]

Wrong separation between lines


t:  41%|████████████████████▊                              | 198/485 [00:42<01:03,  4.55it/s, now=None]

Wrong separation between lines


t:  41%|████████████████████▉                              | 199/485 [00:42<01:02,  4.55it/s, now=None]

Wrong separation between lines


t:  41%|█████████████████████                              | 200/485 [00:43<01:03,  4.47it/s, now=None]

Wrong separation between lines


t:  41%|█████████████████████▏                             | 201/485 [00:43<01:02,  4.54it/s, now=None]

Wrong separation between lines


t:  42%|█████████████████████▏                             | 202/485 [00:43<01:01,  4.57it/s, now=None]

Wrong separation between lines


t:  42%|█████████████████████▎                             | 203/485 [00:43<01:00,  4.62it/s, now=None]

Wrong separation between lines


t:  42%|█████████████████████▍                             | 204/485 [00:44<01:01,  4.58it/s, now=None]

Wrong separation between lines


t:  42%|█████████████████████▌                             | 205/485 [00:44<01:00,  4.62it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  43%|█████████████████████▊                             | 207/485 [00:44<00:58,  4.71it/s, now=None]

Wrong separation between lines


t:  43%|█████████████████████▊                             | 208/485 [00:44<01:00,  4.55it/s, now=None]

Wrong separation between lines


t:  43%|█████████████████████▉                             | 209/485 [00:45<01:00,  4.55it/s, now=None]

Wrong separation between lines


t:  43%|██████████████████████                             | 210/485 [00:45<01:00,  4.53it/s, now=None]

Wrong separation between lines


t:  44%|██████████████████████▏                            | 211/485 [00:45<01:00,  4.55it/s, now=None]

Wrong separation between lines


t:  44%|██████████████████████▎                            | 212/485 [00:45<01:00,  4.55it/s, now=None]

Wrong separation between lines


t:  44%|██████████████████████▍                            | 213/485 [00:46<00:58,  4.61it/s, now=None]

Wrong separation between lines
missdetection
[ 4.21164911e-04 -4.69178624e-01  1.25280810e+02]
Wrong separation between lines


t:  44%|██████████████████████▌                            | 215/485 [00:46<00:58,  4.64it/s, now=None]

missdetection
[ 6.42292124e-04 -6.58934843e-01  1.50924165e+02]
Wrong separation between lines


t:  45%|██████████████████████▋                            | 216/485 [00:46<01:01,  4.39it/s, now=None]

missdetection
[ 7.65485840e-04 -7.86561806e-01  1.79605885e+02]
Wrong separation between lines


t:  45%|██████████████████████▊                            | 217/485 [00:46<01:01,  4.37it/s, now=None]

missdetection
[ 8.49989045e-04 -8.61219235e-01  1.90758370e+02]
Wrong separation between lines


t:  45%|██████████████████████▉                            | 218/485 [00:47<01:00,  4.40it/s, now=None]

missdetection
[ 8.44609679e-04 -9.44041188e-01  2.51125096e+02]
Wrong separation between lines


t:  45%|███████████████████████                            | 219/485 [00:47<01:00,  4.43it/s, now=None]

Wrong separation between lines


t:  45%|███████████████████████▏                           | 220/485 [00:47<00:58,  4.52it/s, now=None]

missdetection
[ 1.19732047e-03 -1.41623555e+00  4.08638653e+02]
Wrong separation between lines


t:  46%|███████████████████████▏                           | 221/485 [00:47<01:00,  4.38it/s, now=None]

Wrong separation between lines


t:  46%|███████████████████████▎                           | 222/485 [00:48<00:59,  4.45it/s, now=None]

missdetection
[ 1.54551676e-03 -1.96771172e+00  6.22795500e+02]
Wrong separation between lines


t:  46%|███████████████████████▍                           | 223/485 [00:48<00:58,  4.47it/s, now=None]

missdetection
[ 1.27563031e-03 -1.63125148e+00  5.19453621e+02]
Wrong separation between lines
missdetection
[ 1.18175234e-03 -1.51091023e+00  4.81397095e+02]
Wrong separation between lines


t:  46%|███████████████████████▋                           | 225/485 [00:48<00:57,  4.49it/s, now=None]

missdetection
[ 1.75363168e-03 -2.38820853e+00  8.13715001e+02]
Wrong separation between lines
Wrong separation between lines


t:  47%|███████████████████████▊                           | 227/485 [00:49<00:55,  4.63it/s, now=None]

missdetection
[ 1.58699282e-03 -2.07810258e+00  6.79626666e+02]
Wrong separation between lines
missdetection
[ 7.20455984e-04 -8.33361391e-01  2.34798583e+02]
Wrong separation between lines


t:  47%|████████████████████████                           | 229/485 [00:49<00:54,  4.69it/s, now=None]

missdetection
[ 7.12232940e-04 -8.43738455e-01  2.45413473e+02]
Wrong separation between lines


t:  47%|████████████████████████▏                          | 230/485 [00:49<00:55,  4.56it/s, now=None]

missdetection
[ 1.16816980e-03 -1.40080660e+00  4.12671934e+02]
Wrong separation between lines


t:  48%|████████████████████████▎                          | 231/485 [00:50<00:54,  4.62it/s, now=None]

missdetection
[ 1.53765083e-03 -1.97012087e+00  6.27667820e+02]
Wrong separation between lines


t:  48%|████████████████████████▍                          | 232/485 [00:50<00:55,  4.58it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  48%|████████████████████████▌                          | 234/485 [00:50<00:54,  4.63it/s, now=None]

Wrong separation between lines


t:  48%|████████████████████████▋                          | 235/485 [00:50<00:55,  4.51it/s, now=None]

Wrong separation between lines


t:  49%|████████████████████████▊                          | 236/485 [00:51<00:54,  4.56it/s, now=None]

missdetection
[ 1.77177599e-03 -2.41530996e+00  8.23520600e+02]
Wrong separation between lines


t:  49%|████████████████████████▉                          | 237/485 [00:51<00:54,  4.53it/s, now=None]

missdetection
[ 1.72395204e-03 -2.30153772e+00  7.70157683e+02]
Wrong separation between lines


t:  49%|█████████████████████████                          | 238/485 [00:51<00:54,  4.50it/s, now=None]

missdetection
[ 1.76590458e-03 -2.37931585e+00  8.02801087e+02]
Wrong separation between lines


t:  49%|█████████████████████████▏                         | 239/485 [00:51<00:54,  4.48it/s, now=None]

missdetection
[ 1.70033417e-03 -2.24962663e+00  7.44550883e+02]
Wrong separation between lines


t:  49%|█████████████████████████▏                         | 240/485 [00:52<00:54,  4.51it/s, now=None]

missdetection
[ 8.17253447e-04 -1.02086703e+00  3.18319953e+02]
Wrong separation between lines


t:  50%|█████████████████████████▎                         | 241/485 [00:52<00:54,  4.45it/s, now=None]

missdetection
[ 9.09997048e-04 -1.15165076e+00  3.64474976e+02]
Wrong separation between lines
missdetection
[ 1.63371035e-04 -2.63153810e-01  1.06949646e+02]
Wrong separation between lines


t:  50%|█████████████████████████▌                         | 243/485 [00:52<00:52,  4.61it/s, now=None]

Wrong separation between lines


t:  50%|█████████████████████████▋                         | 244/485 [00:52<00:51,  4.70it/s, now=None]

Wrong separation between lines


t:  51%|█████████████████████████▊                         | 245/485 [00:53<00:52,  4.57it/s, now=None]

Wrong separation between lines


t:  51%|█████████████████████████▊                         | 246/485 [00:53<00:52,  4.54it/s, now=None]

missdetection
[ 6.27221391e-04 -7.24606000e-01  2.04251106e+02]
Wrong separation between lines


t:  51%|█████████████████████████▉                         | 247/485 [00:53<00:51,  4.60it/s, now=None]

missdetection
[ 8.01863442e-04 -9.58760682e-01  2.81713117e+02]
Wrong separation between lines
missdetection
[ 3.99622355e-04 -4.79565402e-01  1.41695837e+02]
Wrong separation between lines


t:  51%|██████████████████████████▏                        | 249/485 [00:53<00:50,  4.64it/s, now=None]

missdetection
[ 1.45531798e-03 -1.81468143e+00  5.63676078e+02]
Wrong separation between lines


t:  52%|██████████████████████████▎                        | 250/485 [00:54<00:50,  4.66it/s, now=None]

missdetection
[ 1.80301376e-03 -2.35534730e+00  7.70708065e+02]
Wrong separation between lines


t:  52%|██████████████████████████▍                        | 251/485 [00:54<00:50,  4.61it/s, now=None]

Wrong separation between lines


t:  52%|██████████████████████████▍                        | 252/485 [00:54<00:50,  4.63it/s, now=None]

missdetection
[ 2.54256624e-04 -3.44516249e-01  1.18923339e+02]
Wrong separation between lines
Wrong separation between lines


t:  52%|██████████████████████████▋                        | 254/485 [00:55<00:49,  4.65it/s, now=None]

missdetection
[ 4.99608873e-04 -5.48665111e-01  1.43321666e+02]
Wrong separation between lines


t:  53%|██████████████████████████▊                        | 255/485 [00:55<00:50,  4.58it/s, now=None]

missdetection
[ 7.75548860e-04 -9.58892100e-01  2.96650691e+02]
Wrong separation between lines


t:  53%|██████████████████████████▉                        | 256/485 [00:55<00:50,  4.54it/s, now=None]

missdetection
[ 1.67290813e-03 -2.19476473e+00  7.20199761e+02]
Wrong separation between lines


t:  53%|███████████████████████████                        | 257/485 [00:55<00:49,  4.61it/s, now=None]

missdetection
[ 5.12682527e-04 -5.16915998e-01  1.14729377e+02]
Wrong separation between lines


t:  53%|███████████████████████████▏                       | 258/485 [00:55<00:49,  4.62it/s, now=None]

missdetection
[ 6.50254276e-04 -6.68165777e-01  1.54692873e+02]
Wrong separation between lines


t:  53%|███████████████████████████▏                       | 259/485 [00:56<00:49,  4.59it/s, now=None]

missdetection
[ 1.08646594e-03 -1.32629249e+00  3.98919700e+02]
Wrong separation between lines


t:  54%|███████████████████████████▎                       | 260/485 [00:56<00:48,  4.64it/s, now=None]

missdetection
[ 9.10831759e-04 -1.03793018e+00  2.82911420e+02]
Wrong separation between lines


t:  54%|███████████████████████████▍                       | 261/485 [00:56<00:48,  4.63it/s, now=None]

missdetection
[ 9.02791071e-04 -1.04760721e+00  2.94754392e+02]
Wrong separation between lines


t:  54%|███████████████████████████▌                       | 262/485 [00:56<00:47,  4.67it/s, now=None]

missdetection
[ 1.31340528e-03 -1.61074257e+00  4.86913115e+02]
Wrong separation between lines
missdetection
[ 1.37524996e-03 -1.71773720e+00  5.31508068e+02]
Wrong separation between lines


t:  54%|███████████████████████████▊                       | 264/485 [00:57<00:47,  4.69it/s, now=None]

missdetection
[ 1.38122858e-03 -1.72294104e+00  5.33073043e+02]
Wrong separation between lines


t:  55%|███████████████████████████▊                       | 265/485 [00:57<00:47,  4.67it/s, now=None]

missdetection
[ 1.53273200e-03 -1.95878954e+00  6.22270877e+02]
Wrong separation between lines
missdetection
[ 1.60412817e-03 -2.07086306e+00  6.65347024e+02]
Wrong separation between lines


t:  55%|████████████████████████████                       | 267/485 [00:57<00:45,  4.76it/s, now=None]

missdetection
[ 1.20745895e-03 -1.51461801e+00  4.72054379e+02]
Wrong separation between lines


t:  55%|████████████████████████████▏                      | 268/485 [00:58<00:46,  4.72it/s, now=None]

missdetection
[ 5.35312808e-04 -6.45894948e-01  1.92694624e+02]
Wrong separation between lines


t:  55%|████████████████████████████▎                      | 269/485 [00:58<00:45,  4.72it/s, now=None]

missdetection
[ 7.61396243e-04 -9.16114120e-01  2.71184468e+02]
Wrong separation between lines


t:  56%|████████████████████████████▍                      | 270/485 [00:58<00:46,  4.67it/s, now=None]

missdetection
[ 8.48908867e-04 -1.02609774e+00  3.05089830e+02]
Wrong separation between lines


t:  56%|████████████████████████████▍                      | 271/485 [00:58<00:45,  4.68it/s, now=None]

missdetection
[ 1.09643470e-03 -1.37186998e+00  4.28560608e+02]
Wrong separation between lines


t:  56%|████████████████████████████▌                      | 272/485 [00:58<00:47,  4.51it/s, now=None]

missdetection
[ 1.21729010e-03 -1.48721020e+00  4.48411854e+02]
Wrong separation between lines


t:  56%|████████████████████████████▋                      | 273/485 [00:59<00:47,  4.48it/s, now=None]

missdetection
[ 1.17805645e-03 -1.43049247e+00  4.27980969e+02]
Wrong separation between lines


t:  56%|████████████████████████████▊                      | 274/485 [00:59<00:46,  4.53it/s, now=None]

missdetection
[ 1.32520648e-03 -1.71292596e+00  5.50750401e+02]
Wrong separation between lines


t:  57%|████████████████████████████▉                      | 275/485 [00:59<00:46,  4.51it/s, now=None]

Wrong separation between lines


t:  57%|█████████████████████████████                      | 276/485 [00:59<00:46,  4.53it/s, now=None]

Wrong separation between lines


t:  57%|█████████████████████████████▏                     | 277/485 [00:59<00:45,  4.58it/s, now=None]

Wrong separation between lines


t:  57%|█████████████████████████████▏                     | 278/485 [01:00<00:45,  4.52it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  58%|█████████████████████████████▍                     | 280/485 [01:00<00:44,  4.64it/s, now=None]

missdetection
[ 4.06891820e-04 -5.22172056e-01  1.68431008e+02]
Wrong separation between lines
Wrong separation between lines


t:  58%|█████████████████████████████▋                     | 282/485 [01:01<00:44,  4.60it/s, now=None]

missdetection
[ 3.51904127e-04 -4.33240771e-01  1.32896955e+02]
Wrong separation between lines
Wrong separation between lines


t:  58%|█████████████████████████████▊                     | 283/485 [01:01<00:43,  4.60it/s, now=None]

Wrong separation between lines


t:  59%|█████████████████████████████▉                     | 285/485 [01:01<00:42,  4.70it/s, now=None]

Wrong separation between lines


t:  59%|██████████████████████████████                     | 286/485 [01:01<00:42,  4.66it/s, now=None]

missdetection
[ 8.01968767e-04 -1.04201074e+00  3.37075541e+02]
Wrong separation between lines


t:  59%|██████████████████████████████▏                    | 287/485 [01:02<00:43,  4.56it/s, now=None]

Wrong separation between lines


t:  59%|██████████████████████████████▎                    | 288/485 [01:02<00:42,  4.59it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  60%|██████████████████████████████▍                    | 290/485 [01:02<00:41,  4.64it/s, now=None]

Wrong separation between lines


t:  60%|██████████████████████████████▌                    | 291/485 [01:03<00:42,  4.51it/s, now=None]

Wrong separation between lines


t:  60%|██████████████████████████████▋                    | 292/485 [01:03<00:42,  4.54it/s, now=None]

Wrong separation between lines


t:  60%|██████████████████████████████▊                    | 293/485 [01:03<00:42,  4.56it/s, now=None]

Wrong separation between lines


t:  61%|██████████████████████████████▉                    | 294/485 [01:03<00:40,  4.66it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  61%|███████████████████████████████▏                   | 296/485 [01:04<00:39,  4.73it/s, now=None]

Wrong separation between lines


t:  61%|███████████████████████████████▏                   | 297/485 [01:04<00:40,  4.66it/s, now=None]

Wrong separation between lines


t:  61%|███████████████████████████████▎                   | 298/485 [01:04<00:39,  4.73it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  62%|███████████████████████████████▌                   | 300/485 [01:04<00:38,  4.85it/s, now=None]

Wrong separation between lines


t:  62%|███████████████████████████████▋                   | 301/485 [01:05<00:38,  4.77it/s, now=None]

Wrong separation between lines


t:  62%|███████████████████████████████▊                   | 302/485 [01:05<00:39,  4.69it/s, now=None]

missdetection
[ 5.51892253e-04 -7.01736712e-01  2.24888258e+02]
Wrong separation between lines


t:  62%|███████████████████████████████▊                   | 303/485 [01:05<00:39,  4.59it/s, now=None]

missdetection
[ 6.77781032e-04 -7.84106508e-01  2.16566806e+02]
Wrong separation between lines


t:  63%|███████████████████████████████▉                   | 304/485 [01:05<00:39,  4.61it/s, now=None]

missdetection
[ 4.39164860e-04 -4.95811590e-01  1.36238131e+02]
Wrong separation between lines


t:  63%|████████████████████████████████                   | 305/485 [01:06<00:39,  4.55it/s, now=None]

missdetection
[ 7.05221828e-04 -8.58121896e-01  2.58619850e+02]
Wrong separation between lines


t:  63%|████████████████████████████████▏                  | 306/485 [01:06<00:39,  4.54it/s, now=None]

Wrong separation between lines


t:  63%|████████████████████████████████▎                  | 307/485 [01:06<00:39,  4.51it/s, now=None]

Wrong separation between lines


t:  64%|████████████████████████████████▍                  | 308/485 [01:06<00:38,  4.54it/s, now=None]

Wrong separation between lines


t:  64%|████████████████████████████████▍                  | 309/485 [01:06<00:38,  4.60it/s, now=None]

Wrong separation between lines


t:  64%|████████████████████████████████▌                  | 310/485 [01:07<00:38,  4.60it/s, now=None]

Wrong separation between lines


t:  64%|████████████████████████████████▋                  | 311/485 [01:07<00:37,  4.63it/s, now=None]

Wrong separation between lines
missdetection
[ 3.49231171e-04 -3.99644175e-01  1.10513586e+02]
Wrong separation between lines


t:  65%|████████████████████████████████▉                  | 313/485 [01:07<00:37,  4.64it/s, now=None]

Wrong separation between lines


t:  65%|█████████████████████████████████                  | 314/485 [01:07<00:36,  4.65it/s, now=None]

Wrong separation between lines


t:  65%|█████████████████████████████████                  | 315/485 [01:08<00:37,  4.48it/s, now=None]

Wrong separation between lines


t:  65%|█████████████████████████████████▏                 | 316/485 [01:08<00:37,  4.50it/s, now=None]

Wrong separation between lines


t:  65%|█████████████████████████████████▎                 | 317/485 [01:08<00:36,  4.59it/s, now=None]

Wrong separation between lines


t:  66%|█████████████████████████████████▍                 | 318/485 [01:08<00:36,  4.55it/s, now=None]

Wrong separation between lines


t:  66%|█████████████████████████████████▌                 | 319/485 [01:09<00:37,  4.47it/s, now=None]

Wrong separation between lines


t:  66%|█████████████████████████████████▋                 | 320/485 [01:09<00:36,  4.52it/s, now=None]

Wrong separation between lines


t:  66%|█████████████████████████████████▊                 | 321/485 [01:09<00:35,  4.58it/s, now=None]

Wrong separation between lines


t:  66%|█████████████████████████████████▊                 | 322/485 [01:09<00:35,  4.53it/s, now=None]

Wrong separation between lines


t:  67%|█████████████████████████████████▉                 | 323/485 [01:09<00:35,  4.51it/s, now=None]

Wrong separation between lines


t:  67%|██████████████████████████████████                 | 324/485 [01:10<00:35,  4.52it/s, now=None]

Wrong separation between lines


t:  67%|██████████████████████████████████▏                | 325/485 [01:10<00:35,  4.54it/s, now=None]

Wrong separation between lines


t:  67%|██████████████████████████████████▎                | 326/485 [01:10<00:34,  4.56it/s, now=None]

Wrong separation between lines


t:  67%|██████████████████████████████████▍                | 327/485 [01:10<00:34,  4.55it/s, now=None]

Wrong separation between lines


t:  68%|██████████████████████████████████▍                | 328/485 [01:11<00:33,  4.64it/s, now=None]

Wrong separation between lines


t:  68%|██████████████████████████████████▌                | 329/485 [01:11<00:33,  4.63it/s, now=None]

Wrong separation between lines


t:  68%|██████████████████████████████████▋                | 330/485 [01:11<00:34,  4.51it/s, now=None]

Wrong separation between lines


t:  68%|██████████████████████████████████▊                | 331/485 [01:11<00:34,  4.46it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  69%|███████████████████████████████████                | 333/485 [01:12<00:32,  4.65it/s, now=None]

Wrong separation between lines


t:  69%|███████████████████████████████████                | 334/485 [01:12<00:33,  4.54it/s, now=None]

Wrong separation between lines


t:  69%|███████████████████████████████████▏               | 335/485 [01:12<00:32,  4.61it/s, now=None]

Wrong separation between lines


t:  69%|███████████████████████████████████▎               | 336/485 [01:12<00:32,  4.56it/s, now=None]

Wrong separation between lines


t:  69%|███████████████████████████████████▍               | 337/485 [01:13<00:33,  4.41it/s, now=None]

Wrong separation between lines


t:  70%|███████████████████████████████████▌               | 338/485 [01:13<00:33,  4.39it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  70%|███████████████████████████████████▊               | 340/485 [01:13<00:31,  4.65it/s, now=None]

Wrong separation between lines


t:  70%|███████████████████████████████████▊               | 341/485 [01:13<00:31,  4.56it/s, now=None]

Wrong separation between lines


t:  71%|███████████████████████████████████▉               | 342/485 [01:14<00:31,  4.55it/s, now=None]

Wrong separation between lines


t:  71%|████████████████████████████████████               | 343/485 [01:14<00:31,  4.54it/s, now=None]

Wrong separation between lines


t:  71%|████████████████████████████████████▏              | 344/485 [01:14<00:30,  4.58it/s, now=None]

Wrong separation between lines
Wrong separation between lines


t:  71%|████████████████████████████████████▍              | 346/485 [01:14<00:28,  4.82it/s, now=None]

Wrong separation between lines


In [ ]:
HTML("""
<video width="960" height="540" controls>
  <source src="{0}">
</video>
""".format(challenge_output))

In [ ]:
# Instanciate cLine classes
lineLeft = Line()
lineRight = Line()


harder_challenge_output = 'output_videos/harder_challenge_video.mp4'
clip3 = VideoFileClip("test_videos/harder_challenge_video.mp4")

harder_challenge_clip = clip3.fl_image(process_frame) #NOTE: this function expects color images!!
%time harder_challenge_clip.write_videofile(harder_challenge_output, audio=False)

In [ ]:
HTML("""
<video width="960" height="540" controls>
  <source src="{0}">
</video>
""".format(harder_challenge_output))